version: '3'

services:
  db:
    image: postgres
    network_mode: host
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    network_mode: host
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db